"""initial_schema

Revision ID: 8d42f9c69f3a
Revises: 
Create Date: 2026-05-23 16:08:22.452708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d42f9c69f3a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('app_settings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('week_starts_on', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('week_starts_on >= 0 AND week_starts_on <= 6', name='ck_week_starts_on'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('life_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_life_areas_user_name')
    )
    with op.batch_alter_table('life_areas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_life_areas_user_id'), ['user_id'], unique=False)

    op.create_table('quick_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('note_date', sa.Date(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delete_reason', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quick_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quick_notes_user_id'), ['user_id'], unique=False)

    op.create_table('weekly_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('week_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('wins', sa.Text(), nullable=True),
    sa.Column('friction', sa.Text(), nullable=True),
    sa.Column('learnings', sa.Text(), nullable=True),
    sa.Column('emotional_reflection', sa.Text(), nullable=True),
    sa.Column('distractions', sa.Text(), nullable=True),
    sa.Column('direction_state', sa.String(length=16), nullable=True),
    sa.Column('direction_note', sa.String(length=512), nullable=True),
    sa.Column('next_week_intent', sa.Text(), nullable=True),
    sa.Column('casual_notes', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delete_reason', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'week_start', name='uq_weekly_reviews_user_week')
    )
    with op.batch_alter_table('weekly_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weekly_reviews_user_id'), ['user_id'], unique=False)

    op.create_table('life_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('summary', sa.String(length=512), nullable=True),
    sa.Column('motivation', sa.String(length=512), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=True),
    sa.Column('life_area_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delete_reason', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['life_area_id'], ['life_areas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('life_goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_life_goals_user_id'), ['user_id'], unique=False)

    op.create_table('short_term_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('life_goal_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('summary', sa.String(length=512), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delete_reason', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['life_goal_id'], ['life_goals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('short_term_goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_short_term_goals_user_id'), ['user_id'], unique=False)

    op.create_table('weekly_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('summary', sa.String(length=512), nullable=True),
    sa.Column('week_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('week_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('short_term_goal_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delete_reason', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['short_term_goal_id'], ['short_term_goals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weekly_goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weekly_goals_user_id'), ['user_id'], unique=False)

    op.create_table('core_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('weekly_goal_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delete_reason', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['weekly_goal_id'], ['weekly_goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('core_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_core_tasks_user_id'), ['user_id'], unique=False)

    op.create_table('momentum_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('change', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('core_task_id', sa.Integer(), nullable=True),
    sa.Column('weekly_review_id', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['core_task_id'], ['core_tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['weekly_review_id'], ['weekly_reviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('momentum_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_momentum_events_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('momentum_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_momentum_events_user_id'))

    op.drop_table('momentum_events')
    with op.batch_alter_table('core_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_core_tasks_user_id'))

    op.drop_table('core_tasks')
    with op.batch_alter_table('weekly_goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weekly_goals_user_id'))

    op.drop_table('weekly_goals')
    with op.batch_alter_table('short_term_goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_short_term_goals_user_id'))

    op.drop_table('short_term_goals')
    with op.batch_alter_table('life_goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_life_goals_user_id'))

    op.drop_table('life_goals')
    with op.batch_alter_table('weekly_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weekly_reviews_user_id'))

    op.drop_table('weekly_reviews')
    with op.batch_alter_table('quick_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quick_notes_user_id'))

    op.drop_table('quick_notes')
    with op.batch_alter_table('life_areas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_life_areas_user_id'))

    op.drop_table('life_areas')
    op.drop_table('app_settings')
    op.drop_table('users')
    # ### end Alembic commands ###
